version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: health_indicators

models:
  - name: stg_health_indicators
    columns:
      - name: country
        tests:
          - not_null
      - name: iso_code
        tests:
          - not_null
      - name: year
        tests:
          - not_null
  - name: mart_country_health_trends
    columns:
      - name: country
        tests:
          - not_null
      - name: year
        tests:
          - not_null
